### ISSUE TITLE
Text Alignment (TextRoundCorner )

### ISSUE THREAD

**Issue by mzdevmarco** [akexorcist/Android-RoundCornerProgressBar#41]
Hello, nice work. I would like to suggest a new feature.  Like set the property Text Alignment  on the TextRoundCorner (Center, Left or Right) 

Or is it already implemented?

Regards

**Comment by akexorcist** [comment]
That's interesting. I may add this function in the next update.

**Comment by XxGoliathusxX** [comment]
Is this still in progress?

**Comment by chnouman** [comment]
any update?

**Comment by akexorcist** [comment]
Left and right are OK but center does not support (because textview's width in the RelativeLayout doesn't wrap_content correctly when align center)

So in version 2.1.0, you can set the text gravity with `start` or `end` in TextRoundCornerProgressBar 

```xml
app:rcTextInsideGravity="end"
app:rcTextOutsideGravity="start"
```

See https://github.com/akexorcist/Android-RoundCornerProgressBar/commit/4f4302703e870fa3ce479371a7742f6c32f31d96
