### ISSUE TITLE
TextRoundCornerProgressBar alignment of text .

### ISSUE THREAD

**Issue by altaf933** [akexorcist/Android-RoundCornerProgressBar#50]
I have used  TextRoundCornerProgressBar and i want to suggest a enhancement of text gravity .
Currently it's rendering left of progress view and we can add this alignment as per user oriented like left,right or center.

**Comment by akexorcist** [comment]
Left and right are OK but center does not support (because RelativeLayout and the textview's width doesn't wrap_content correctly when align center)

So in version 2.1.0 you can set the text gravity with `start` or `end` in TextRoundCornerProgressBar 

```xml
app:rcTextInsideGravity="end"
app:rcTextOutsideGravity="start"
```

See https://github.com/akexorcist/Android-RoundCornerProgressBar/commit/4f4302703e870fa3ce479371a7742f6c32f31d96
